### PR TITLE
ANSIescape stopped working in Sublime 3.1

### PR DESCRIPTION
**Pull request by lassevalentini**
Happened due to breaking changes in the Default example plugin exec.py. 
Included the exec.py from the previous version of sublime instead.

### CODE REVIEW

**Comment by jfcherng** [comment]
Thank you :+1:

**Comment by jfcherng** [comment]
Unfortunately, this patch makes my ST pop up `__init__() got an unexpected keyword argument 'update_phantoms_only'` every time I open a file so I have to reverse this patch.

**Comment by lassevalentini** [comment]
Seems like the correct thing to do is use the new exec and add reverese compatibility.
I think the problem is that in the previous version, the data argument in on_data were a byte array, where now it is a string.
Should I try to detect if it is a byte array and just do encoding/decoding based on that?

**Comment by jfcherng** [comment]
That looks good. 

The new `exec.py` removes following codes from its `on_data`.
```diff
     def on_data(self, proc, data):
-        try:
-            characters = data.decode(self.encoding)
-        except:
-            characters = "[Decode error - output not " + self.encoding + "]\n"
-            proc = None
```

We could prepend it back to our own `on_data` and make some modification to it if necessary.

**Comment by jfcherng** [comment]
I notice that there is no codec-related codes in `class ExecCommand(sublime_plugin.WindowCommand, ProcessListener)` in the new `exec.py`.

It looks like just removing the encoding/decoding related code in `    def on_data_process(self, proc, data):` make this plugin working again.

**Comment by jfcherng** [comment]
Could you try the code in https://github.com/aziz/SublimeANSI/tree/fix-st-3170 branch?

**Comment by jfcherng** [comment]
Commit https://github.com/aziz/SublimeANSI/commit/d5ac09de5d5fb6effa46ee59354f869851a0c52d would take care of BC.
